// g:\Shubham Personal Projects\Personal projects\Grocery Shop Prices\Grocery-Shop-Prices\lib\methods\general.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'compressFile.dart';
export 'createFadeTransitionRouteFor000.dart';
export 'goToScreenFor000.dart';
export 'goToWithTransitionToScreenFor000.dart';
export 'setGlobalDimensions.dart';
export 'uploadDocument.dart';
export 'uploadUserImagePath.dart';