// g:\Shubham Personal Projects\Personal projects\Grocery Shop Prices\Grocery-Shop-Prices\lib\dialogs.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'addNewRatesForItemDialog.dart';
export 'itemdetaildialog.dart';